<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<AssemblyName>PlentyODarts</AssemblyName>		
		<TargetFramework>net8.0</TargetFramework>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
	  <Reference Include="ParticleLibrary">
	    <HintPath>lib\ParticleLibrary.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<!-- References -->

</Project>